# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.iplus <- function(x, y) {
    .Call(`_intarith_plus`, x, y)
}

.iminus <- function(x, y) {
    .Call(`_intarith_minus`, x, y)
}

.imult <- function(x, y) {
    .Call(`_intarith_mult`, x, y)
}

rcpp_hello_world <- function() {
    .Call(`_intarith_rcpp_hello_world`)
}

.iplus <- function(x, y) {
    .Call(`_intarith_rcpp_plus`, x, y)
}

.iminus <- function(x, y) {
    .Call(`_intarith_rcpp_minus`, x, y)
}

